#!/usr/bin/env python3
"""Size the drafted search blocks in draft/blocks_pubmed.yml against live PubMed.

Usage: python3 scripts/test_draft.py [--write]
       --write  regenerate draft/counts.md

Reports the yield of each block alone and of each combination, so the cost of every
design decision (adding an age filter, adding an outcome block, adding a design filter)
is a number rather than an opinion. Also reports any term PubMed could not match.
"""
import json
import os
import re
import sys
import time
import urllib.parse
import urllib.request

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "draft", "blocks_pubmed.yml")
EUT = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi"
UA = {"User-Agent": "sunami-lab-review/1.0 (mailto:chenyangsu87@gmail.com)"}


def run(term):
    """POST, not GET - the unioned outcome block exceeds the URI length limit."""
    data = urllib.parse.urlencode(
        {"db": "pubmed", "retmode": "json", "retmax": "0", "term": term}).encode()
    for attempt in range(3):
        try:
            return json.loads(urllib.request.urlopen(
                urllib.request.Request(EUT, data=data, headers=UA),
                timeout=120).read())["esearchresult"]
        except Exception:
            if attempt == 2:
                raise
            time.sleep(4)


def flat(q):
    return re.sub(r"\s+", " ", q).strip()


def main():
    d = yaml.safe_load(open(SRC))
    blocks, combos = d["blocks"], d["combinations"]

    print("=== individual blocks ===")
    brows = []
    for k, b in blocks.items():
        r = run(f"({flat(b['query'])})")
        miss = ((r.get("errorlist", {}) or {}).get("phrasesnotfound") or []) + \
               ((r.get("warninglist", {}) or {}).get("quotedphrasesnotfound") or [])
        brows.append((k, b["label"], int(r.get("count", 0)), miss))
        print(f"  {int(r.get('count',0)):>10,}  {k:<16} {b['label']}")
        if miss:
            print(f"              unmatched: {', '.join(miss[:8])}")
        time.sleep(0.4)

    print("\n=== combinations ===")
    crows = []
    for c in combos:
        parts = [f"({flat(blocks[b]['query'])})" for b in c["and"]]
        if c.get("or_group"):
            parts.append("(" + " OR ".join(
                f"({flat(blocks[b]['query'])})" for b in c["or_group"]) + ")")
        r = run(" AND ".join(parts))
        crows.append((c["id"], int(r.get("count", 0))))
        print(f"  {int(r.get('count',0)):>10,}  {c['id']}")
        time.sleep(0.4)

    if "--write" in sys.argv:
        p = os.path.join(ROOT, "draft", "counts.md")
        L = ["# Drafted strategy - PubMed yields", "",
             "Generated by `python3 scripts/test_draft.py --write` from",
             "`draft/blocks_pubmed.yml`. Counts are live PubMed and will drift upward; the",
             "ratios are the point, not the absolute numbers.", "",
             "## Blocks in isolation", "",
             "| Block | Concept | PubMed records | Terms not matched |", "|---|---|---:|---|"]
        for k, lab, n, miss in brows:
            L.append(f"| `{k}` | {lab} | {n:,} | {', '.join(miss[:4]) or 'none'} |")
        L += ["", "## Combinations", "",
              "| Strategy | PubMed records |", "|---|---:|"]
        for cid, n in crows:
            L.append(f"| {cid} | {n:,} |")
        base = dict(crows).get("P AND I")
        if base:
            L += ["", "## What each decision costs", "",
                  f"Taking `P AND I` = {base:,} records as the reference:", ""]
            for cid, n in crows:
                if cid in ("P", "P AND I"):
                    continue
                pct = 100.0 * n / base
                L.append(f"- **{cid}** retains {n:,} records, {pct:.1f}% of the "
                         f"population-and-intervention set.")
        open(p, "w").write("\n".join(L) + "\n")
        print("\nwrote draft/counts.md")


if __name__ == "__main__":
    main()
