#!/usr/bin/env python3
"""Run the transcribed PubMed strategies against E-utilities and report what PubMed
actually did with them.

Usage: python3 scripts/validate_pubmed.py [--write]
       --write  also regenerate docs/validation.md

A strategy that returns 0 hits, or whose translation shows a dropped term, has a
transcription or a syntax problem. PubMed reports unmatched terms in `errorlist` and
`warninglist`, which is the point of running this rather than eyeballing the strings.
"""
import json
import os
import re
import sys
import time
import urllib.parse
import urllib.request

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def stamp():
    """UTC date of this run, so a quoted count can always be dated."""
    import datetime
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
EUT = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi"
UA = {"User-Agent": "sunami-lab-review/1.0 (mailto:chenyangsu87@gmail.com)"}


def run(term):
    url = f"{EUT}?db=pubmed&retmode=json&retmax=0&term={urllib.parse.quote(term)}"
    req = urllib.request.Request(url, headers=UA)
    for attempt in range(3):
        try:
            return json.loads(urllib.request.urlopen(req, timeout=90).read())["esearchresult"]
        except Exception:
            if attempt == 2:
                raise
            time.sleep(3)


def main():
    tests = yaml.safe_load(open(os.path.join(ROOT, "data", "pubmed_tests.yml")))["tests"]
    rows = []
    for t in tests:
        term = re.sub(r"\s+", " ", t["query"]).strip()
        r = run(term)
        count = int(r.get("count", 0))
        el = r.get("errorlist", {}) or {}
        wl = r.get("warninglist", {}) or {}
        dropped = (el.get("phrasesnotfound") or []) + (el.get("fieldsnotfound") or [])
        quoted = wl.get("quotedphrasesnotfound") or []
        rows.append(dict(id=t["id"], record=t["record"], note=t.get("note", ""),
                         count=count, dropped=dropped, quoted=quoted,
                         translation=r.get("querytranslation", "")))
        flag = "FAIL" if count == 0 else ("WARN" if dropped or quoted else "ok  ")
        print(f"{flag}  {count:>9,}  {t['id']}")
        if dropped:
            print(f"          terms PubMed could not match: {', '.join(dropped[:8])}")
        if quoted:
            print(f"          quoted phrases not found:     {', '.join(quoted[:8])}")
        time.sleep(0.4)

    if "--write" in sys.argv:
        p = os.path.join(ROOT, "docs", "validation.md")
        L = ["# PubMed validation run", "",
             f"_Run {stamp()}._", "",
             "Generated by `python3 scripts/validate_pubmed.py --write` against the strings in",
             "`data/pubmed_tests.yml`. Counts move as PubMed grows; what matters is that each",
             "strategy parses, returns a plausible number, and that no term is silently dropped.",
             ""]
        L += ["| Strategy | Hits | Terms PubMed could not match |", "|---|---:|---|"]
        for r in rows:
            miss = ", ".join((r["dropped"] + r["quoted"])[:6]) or "none"
            L.append(f"| `{r['id']}` | {r['count']:,} | {miss} |")
        L += ["", "## Detail", ""]
        for r in rows:
            L += [f"### `{r['id']}`", "", f"**{r['record']}**", "",
                  f"- Hits: **{r['count']:,}**"]
            if r["note"]:
                L.append(f"- Transcription note: {r['note']}")
            if r["dropped"] or r["quoted"]:
                L.append(f"- Unmatched: {', '.join(r['dropped'] + r['quoted'])}")
            L += ["", "PubMed's translation:", "", "```", r["translation"], "```", ""]
        open(p, "w").write("\n".join(L) + "\n")
        print("\nwrote docs/validation.md")


if __name__ == "__main__":
    main()
